name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库

      - name: Deploy to Server # 第二步，rsync推文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.SSH_SECRET }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: "22" # SSH端口
          FOLDER: ./ # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SSH_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: ${{ secrets.DEPLOY_PATH }} # 部署到目标文件夹
      # - name: Restart server # 第三步，重启服务
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }} # 下面三个配置与上一步类似
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_SECRET }}
      #     script: |
      #       sudo supervisorctl restart mp_game

